# Environment only: the license-free MATLAB Runtime (no algorithm code copied in).
# The compiled `recon` binary + run.sh live in this folder and are mounted at /algo at run time.
# Match the Runtime version to the MATLAB Compiler used to build `recon` (see BUILD.md).
FROM containers.mathworks.com/matlab-runtime:r2023b
