#!/usr/bin/env bash
# Runs the MATLAB-compiled `recon` binary on the MATLAB Runtime. The MCR wrapper generated by mcc
# sets LD_LIBRARY_PATH; we just invoke it with the input/output dirs.
set -euo pipefail
IN="${1:-/input}"; OUT="${2:-/output}"
/opt/algo/recon "$IN" "$OUT"
