"""Auto-generate workflow-engine wrappers from the QSM-CI stage contract.

Every QSM-CI algorithm is invoked the same way — ``qsm-ci run <slug> --<artifact> … -o <produced>`` —
and the artifacts each stage consumes/produces are declared once in :mod:`qsm_ci.stages` (mirroring
``stages.yml``). So a wrapper for any workflow engine is just a template over that contract; this
module generates them, which keeps them in lock-step with the contract instead of hand-maintained.

Supported engines (``qsm-ci interface <engine>``):

- ``cwl``       — a CommandLineTool per stage (``$graph`` when several)
- ``snakemake`` — a rule per stage
- ``nextflow``  — a DSL2 process per stage

The container runs underneath the CLI (docker/podman/apptainer/local), so none of the wrappers need
the engine's own container support. The two Python engines ship as ready-to-import modules instead:
:mod:`qsm_ci.nipype` and :mod:`qsm_ci.pydra`.
"""

from __future__ import annotations

from .stages import ARTIFACT_FILE, STAGES, produced_artifact

# Consumed artifacts a stage can run without: magnitude (only some methods use it) and params
# (a caller may pass acquisition flags instead). Everything else a stage consumes is required.
OPTIONAL = {"magnitude", "params"}

CORE_STAGES = ["field-mapping", "bfr", "dipole"]
ENGINES = ("cwl", "snakemake", "nextflow")

STAGE_DESC = {
    "field-mapping": "phase → total field",
    "bfr": "total field → local field",
    "dipole": "local field → susceptibility (χ)",
    "unwrap+bfr": "phase → local field",
    "bfr+dipole": "total field → susceptibility (χ)",
    "end-to-end": "phase → susceptibility (χ)",
}


def _ident(stage: str) -> str:
    """A safe identifier for a stage/span name (``bfr+dipole`` -> ``bfr_dipole``)."""
    return stage.replace("+", "_").replace("-", "_")


def _consumes(stage: str) -> list:
    return STAGES[stage]["consumes"]


# --- CWL --------------------------------------------------------------------------------------

def _cwl_tool(stage: str, indent: str = "") -> str:
    produced = produced_artifact(stage)
    lines = [
        "class: CommandLineTool",
        f"label: QSM-CI {stage} stage ({STAGE_DESC.get(stage, stage)})",
        "baseCommand: [qsm-ci, run]",
        "inputs:",
        "  slug: { type: string, inputBinding: { position: 1 } }",
    ]
    for art in _consumes(stage):
        # quote the optional type — bare `File?` is ambiguous in YAML flow style. position:2 keeps
        # every flag after the positional slug (position:1), else unpositioned flags sort before it.
        t = '"File?"' if art in OPTIONAL else "File"
        lines.append(f"  {art}: {{ type: {t}, inputBinding: {{ prefix: --{art}, position: 2 }} }}")
    lines.append(
        f"  out: {{ type: string, default: {ARTIFACT_FILE[produced]}, "
        f"inputBinding: {{ prefix: -o, position: 2 }} }}")
    lines.append("outputs:")
    lines.append(f"  {produced}: {{ type: File, outputBinding: {{ glob: $(inputs.out) }} }}")
    return "\n".join(indent + ln for ln in lines) if indent else "\n".join(lines)


def _cwl(stages: list) -> str:
    if len(stages) == 1:
        return "cwlVersion: v1.2\n" + _cwl_tool(stages[0]) + "\n"
    out = ["cwlVersion: v1.2", "$graph:"]
    for s in stages:
        out.append(f"  - id: {_ident(s)}")
        out.append(_cwl_tool(s, indent="    "))
    return "\n".join(out) + "\n"


# --- Snakemake --------------------------------------------------------------------------------

def _snakemake_rule(stage: str, slug: str) -> str:
    produced = produced_artifact(stage)
    inputs = "\n".join(f'        {a}="{ARTIFACT_FILE[a]}",' for a in _consumes(stage))
    flags = " ".join(f"--{a} {{input.{a}}}" for a in _consumes(stage))
    return (
        f"rule {_ident(stage)}:\n"
        f"    input:\n{inputs}\n"
        f"    output:\n        {produced}=\"{ARTIFACT_FILE[produced]}\",\n"
        f'    params:\n        slug="{slug}",\n'
        f'    shell:\n        "qsm-ci run {{params.slug}} {flags} -o {{output.{produced}}}"'
    )


def _snakemake(stages: list, slug: str) -> str:
    head = "# QSM-CI Snakemake rules — auto-generated by `qsm-ci interface snakemake`.\n" \
           "# Set params.slug to pick which method runs each stage.\n\n"
    return head + "\n\n".join(_snakemake_rule(s, slug) for s in stages) + "\n"


# --- Nextflow (DSL2) --------------------------------------------------------------------------

def _nextflow_process(stage: str, slug: str) -> str:
    produced = produced_artifact(stage)
    ins = "\n".join(["    val slug"] + [f"    path {a}" for a in _consumes(stage)])
    flags = " ".join(f"--{a} ${{{a}}}" for a in _consumes(stage))
    return (
        f"process {_ident(stage)} {{\n"
        f"    input:\n{ins}\n\n"
        f"    output:\n    path '{ARTIFACT_FILE[produced]}'\n\n"
        f'    script:\n    """\n'
        f"    qsm-ci run ${{slug}} {flags} -o {ARTIFACT_FILE[produced]}\n"
        f'    """\n'
        f"}}"
    )


def _nextflow(stages: list, slug: str) -> str:
    head = "// QSM-CI Nextflow processes — auto-generated by `qsm-ci interface nextflow`.\n" \
           "// The `slug` input picks which method runs each stage.\n" \
           "nextflow.enable.dsl = 2\n\n"
    return head + "\n\n".join(_nextflow_process(s, slug) for s in stages) + "\n"


# --- end-to-end pipeline (a method per stage, chained phase -> chi) ----------------------------

PIPELINE = ["field-mapping", "bfr", "dipole"]  # the canonical phase -> chi chain


def _pipeline_io(stages: list) -> tuple:
    """(produced, top) — produced maps an artifact to the index of the stage that makes it; top is
    the ordered list of artifacts consumed but never produced upstream (the pipeline's own inputs)."""
    produced = {produced_artifact(s): i for i, (s, _) in enumerate(stages)}
    top: list = []
    for s, _ in stages:
        for a in STAGES[s]["consumes"]:
            if a not in produced and a not in top:
                top.append(a)
    return produced, top


def _stages(slugs: list) -> list:
    if len(slugs) != len(PIPELINE):
        raise ValueError(f"pipeline needs {len(PIPELINE)} slugs (field-mapping, bfr, dipole), got {len(slugs)}")
    return list(zip(PIPELINE, slugs))


def _cwl_pipeline(stages: list) -> str:
    produced, top = _pipeline_io(stages)
    final = stages[-1][0]
    fprod = produced_artifact(final)
    out = ["cwlVersion: v1.2", "class: Workflow",
           "# run:  cwltool pipeline.cwl --phase p.nii.gz --magnitude m.nii.gz --mask mask.nii.gz --params p.json",
           "inputs:"]
    out += [f"  {a}: File" for a in top]
    out += ["outputs:", f"  {fprod}:", "    type: File", f"    outputSource: {_ident(final)}/{fprod}",
            "steps:"]
    for stage, slug in stages:
        sid, prod = _ident(stage), produced_artifact(stage)
        out.append(f"  {sid}:")
        out.append("    run:")
        out.append("      class: CommandLineTool")
        out.append("      baseCommand: [qsm-ci, run]")
        out.append("      inputs:")
        out.append(f"        slug: {{ type: string, default: {slug}, inputBinding: {{ position: 1 }} }}")
        for a in STAGES[stage]["consumes"]:
            t = '"File?"' if a in OPTIONAL else "File"
            out.append(f"        {a}: {{ type: {t}, inputBinding: {{ prefix: --{a}, position: 2 }} }}")
        out.append(f"        out: {{ type: string, default: {ARTIFACT_FILE[prod]}, inputBinding: {{ prefix: -o, position: 2 }} }}")
        out.append("      outputs:")
        out.append(f"        {prod}: {{ type: File, outputBinding: {{ glob: {ARTIFACT_FILE[prod]} }} }}")
        out.append("    in:")
        for a in STAGES[stage]["consumes"]:
            src = f"{_ident(stages[produced[a]][0])}/{a}" if a in produced else a
            out.append(f"      {a}: {src}")
        out.append(f"    out: [{prod}]")
    return "\n".join(out) + "\n"


def _snakemake_pipeline(stages: list) -> str:
    head = ("# QSM-CI end-to-end pipeline — auto-generated by `qsm-ci interface snakemake --pipeline`.\n"
            "# Put phase/magnitude/mask/params in the working dir, then:  snakemake -c1 chimap.nii.gz\n"
            "# The rules chain by filename (totalfield -> localfield -> chimap).\n\n")
    return head + "\n\n".join(_snakemake_rule(stage, slug) for stage, slug in stages) + "\n"


def _nextflow_pipeline(stages: list) -> str:
    produced, top = _pipeline_io(stages)
    parts = ["// QSM-CI end-to-end pipeline — auto-generated by `qsm-ci interface nextflow --pipeline`.",
             "// run:  nextflow run qsm.nf --phase p.nii.gz --magnitude m.nii.gz --mask mask.nii.gz \\",
             "//         --params p.json --outdir results",
             "nextflow.enable.dsl = 2", ""]
    parts += [_nextflow_process(stage, slug) + "\n" for stage, slug in stages]
    wf = ["workflow {"]
    for stage, slug in stages:
        sid = _ident(stage)
        args = [f"'{slug}'"]
        for a in STAGES[stage]["consumes"]:
            args.append(f"{_ident(stages[produced[a]][0])}_out" if a in produced else f"file(params.{a})")
        wf.append(f"    {sid}_out = {sid}({', '.join(args)})")
    fprod = produced_artifact(stages[-1][0])
    wf.append(f"    {_ident(stages[-1][0])}_out.collectFile(name: '{ARTIFACT_FILE[fprod]}', "
              "storeDir: params.outdir ?: '.')")
    wf.append("}")
    parts.append("\n".join(wf))
    return "\n".join(parts) + "\n"


_PIPELINE_GENERATORS = {"cwl": _cwl_pipeline, "snakemake": _snakemake_pipeline, "nextflow": _nextflow_pipeline}


def generate_pipeline(engine: str, slugs: list) -> str:
    """Return an end-to-end (phase → χ) pipeline wrapper: field-mapping → bfr → dipole, one method
    (slug) per stage, chained. Only the declarative engines — nipype/pydra compose in Python."""
    if engine not in _PIPELINE_GENERATORS:
        raise ValueError(f"no pipeline generator for '{engine}'; choose from {', '.join(_PIPELINE_GENERATORS)}")
    return _PIPELINE_GENERATORS[engine](_stages(slugs))


# --- entry point ------------------------------------------------------------------------------

_GENERATORS = {
    "cwl": lambda stages, slug: _cwl(stages),
    "snakemake": _snakemake,
    "nextflow": _nextflow,
}


def generate(engine: str, stage: str | None = None, slug: str = "SLUG") -> str:
    """Return the wrapper text for ``engine``. ``stage`` defaults to the three core stages."""
    if engine not in _GENERATORS:
        raise ValueError(f"unknown engine '{engine}'; choose from {', '.join(ENGINES)}")
    if stage is not None and stage not in STAGES:
        raise ValueError(f"unknown stage '{stage}'; choose from {', '.join(STAGES)}")
    stages = [stage] if stage else list(CORE_STAGES)
    return _GENERATORS[engine](stages, slug)
