// QSM-CI end-to-end pipeline — auto-generated by `qsm-ci interface nextflow --pipeline`.
// run:  nextflow run qsm.nf --phase p.nii.gz --magnitude m.nii.gz --mask mask.nii.gz \
//         --params p.json --outdir results
// --magnitude/--params are optional; omit either and the sentinel file('NO_FILE') is staged
// instead (create it once with `touch NO_FILE`) and the flag is dropped.
nextflow.enable.dsl = 2

process field_mapping {
    input:
    val slug
    path phase
    path magnitude      // optional: pass file('NO_FILE') to skip
    path mask
    path params_json      // optional: pass file('NO_FILE') to skip

    output:
    path 'totalfield.nii.gz'

    script:
    def magnitude_flag = magnitude.name == 'NO_FILE' ? '' : "--magnitude ${magnitude}"
    def params_json_flag = params_json.name == 'NO_FILE' ? '' : "--params ${params_json}"
    """
    qsm-ci run ${slug} --phase ${phase} --mask ${mask} ${magnitude_flag} ${params_json_flag} -o totalfield.nii.gz
    """
}

process bfr {
    input:
    val slug
    path totalfield
    path mask
    path params_json      // optional: pass file('NO_FILE') to skip

    output:
    path 'localfield.nii.gz'

    script:
    def params_json_flag = params_json.name == 'NO_FILE' ? '' : "--params ${params_json}"
    """
    qsm-ci run ${slug} --totalfield ${totalfield} --mask ${mask} ${params_json_flag} -o localfield.nii.gz
    """
}

process dipole {
    input:
    val slug
    path localfield
    path mask
    path params_json      // optional: pass file('NO_FILE') to skip

    output:
    path 'chimap.nii.gz'

    script:
    def params_json_flag = params_json.name == 'NO_FILE' ? '' : "--params ${params_json}"
    """
    qsm-ci run ${slug} --localfield ${localfield} --mask ${mask} ${params_json_flag} -o chimap.nii.gz
    """
}

workflow {
    field_mapping_out = field_mapping('romeo-qsmrs', file(params.phase), (params.magnitude ? file(params.magnitude) : file('NO_FILE')), file(params.mask), (params.params ? file(params.params) : file('NO_FILE')))
    bfr_out = bfr('vsharp-qsmrs', field_mapping_out, file(params.mask), (params.params ? file(params.params) : file('NO_FILE')))
    dipole_out = dipole('rts-qsmrs', bfr_out, file(params.mask), (params.params ? file(params.params) : file('NO_FILE')))
    dipole_out.collectFile(name: 'chimap.nii.gz', storeDir: params.outdir ?: '.')
}
