// QSM-CI end-to-end pipeline — auto-generated by `qsm-ci interface nextflow --pipeline`.
// run:  nextflow run qsm.nf --phase p.nii.gz --magnitude m.nii.gz --mask mask.nii.gz \
//         --params p.json --outdir results
nextflow.enable.dsl = 2

process field_mapping {
    input:
    val slug
    path phase
    path magnitude
    path mask
    path params

    output:
    path 'totalfield.nii.gz'

    script:
    """
    qsm-ci run ${slug} --phase ${phase} --magnitude ${magnitude} --mask ${mask} --params ${params} -o totalfield.nii.gz
    """
}

process bfr {
    input:
    val slug
    path totalfield
    path mask
    path params

    output:
    path 'localfield.nii.gz'

    script:
    """
    qsm-ci run ${slug} --totalfield ${totalfield} --mask ${mask} --params ${params} -o localfield.nii.gz
    """
}

process dipole {
    input:
    val slug
    path localfield
    path mask
    path params
    path magnitude

    output:
    path 'chimap.nii.gz'

    script:
    """
    qsm-ci run ${slug} --localfield ${localfield} --mask ${mask} --params ${params} --magnitude ${magnitude} -o chimap.nii.gz
    """
}

workflow {
    field_mapping_out = field_mapping('romeo-fieldmap', file(params.phase), file(params.magnitude), file(params.mask), file(params.params))
    bfr_out = bfr('vsharp', field_mapping_out, file(params.mask), file(params.params))
    dipole_out = dipole('rts', bfr_out, file(params.mask), file(params.params), file(params.magnitude))
    dipole_out.collectFile(name: 'chimap.nii.gz', storeDir: params.outdir ?: '.')
}
