name: Upload to object storage
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: upload
      env:
        OS_PASSWORD: ${{ secrets.SWIFT_OS_PASSWORD }}
        OS_PROJECT_ID: ${{ secrets.SWIFT_OS_PROJECT_ID }}
        OS_USERNAME: ${{ secrets.SWIFT_OS_USERNAME }}
        OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.SWIFT_OS_APPLICATION_CREDENTIAL_ID }}
        OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.SWIFT_OS_APPLICATION_CREDENTIAL_SECRET }}
        PARSE_APPLICATION_ID: ${{ secrets.PARSE_APPLICATION_ID }}
        PARSE_REST_API_KEY: ${{ secrets.PARSE_REST_API_KEY }}
      run: |
        /bin/bash upload.sh
        
